question_data = [
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "The Republic of Malta is the smallest microstate worldwide.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]
    },
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Board Games",
     "question": "Snakes and Ladders was originally created in India?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Books",
     "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel &quot;The Lord of The Rings&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Vehicles",
     "question": "BMW M GmbH is a subsidiary of BMW AG that focuses on car performance.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Politics",
     "question": "There was a satirical candidate named &quot;Deez Nuts&quot; running in the 2016 US presidential elections.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Comics",
     "question": "The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Television",
     "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Codemasters is the developer of the Gran Turismo series.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "The anime &quot;Lucky Star&quot; follows the story of one girl who is unaware she is God.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Music",
     "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "Gumbo is a stew that originated in Louisiana.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Science &amp; Nature",
     "question": "An atom contains a nucleus.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "No Game No Life first aired in 2014.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "The Spitfire originated from a racing plane.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Donkey Kong was originally set to be a Popeye arcade game.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "&quot;Foodfight!&quot; earned less than $80,000 at box office.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Board Games",
     "question": "The card game &quot;Munchkin&quot; won the 2001 Origins Award for Best Traditional Card Game.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "The mitochondria is the powerhouse of the cell.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "The Great Wall of China is visible from the moon.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "Adolf Hitler was tried at the Nuremberg trials.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In &quot;Space Station 13&quot;,  the station has a clown aboard it.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "Ping-Pong originated in England",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "Scotland voted to become an independent country during the referendum from September 2014.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "The Killer Whale is considered a type of dolphin.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "&quot;Undertale&quot; is an RPG created by Toby Fox and released in 2015.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "French is an official language in Canada.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In the Monster Hunter Series, it is possible to capture Elder Dragons.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Activision created Battlefield 1.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Science &amp; Nature",
     "question": "Salt is 100% composed of Sodium.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Music",
     "question": "The song &quot;Stronger Than You&quot; is a single by Estelle, who played Garnet in Steven Universe.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "The game &quot;Jetpack Joyride&quot; was created by &quot;Redbrick Studios&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Music",
     "question": "A Saxophone is a brass instrument.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Mythology",
     "question": "According to Greek Mythology, Atlas was an Olympian God.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "Nova Scotia is on the east coast of Canada.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]
